GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6203023fe517ad3eb56466f7


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web dev Simplified"
}